### ISSUE TITLE
Baltimore Mascot

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaCon/www.juliacon.org#156]
Since Boh is the official "unofficial mascot of Baltimore" I made this graphic for JuliaCon2019: Baltimore Edition. Go O's. 

![julia_boh](https://user-images.githubusercontent.com/2753998/50104303-a5b28200-01f7-11e9-92a7-b7878a7ff409.png) 

We could go with other styles that would take longer to draw. 

![image](https://user-images.githubusercontent.com/2753998/50104427-f9bd6680-01f7-11e9-9b84-01c591c852cd.png)

![image](https://user-images.githubusercontent.com/2753998/50104460-0c37a000-01f8-11e9-8b2b-428a17dbb83d.png)

I have an SVG version but can't attach it to GH issue, or post on discourse.

**Comment by randyzwitch** [comment]
The first one definitely needs to be made into stickers (even if unofficially)

**Comment by jpfairbanks** [comment]
What about one boh, with the four colors, mustache in red/purple eye in green and the outer circle in blue? This is beyond my inkscape skills.

**Comment by cormullion** [comment]
I don't think much of the bow tie idea, sadly... :)

<img width="602" alt="screenshot 2018-12-17 at 20 15 43" src="https://user-images.githubusercontent.com/52289/50112982-97388a80-0238-11e9-997b-1e4c922d787e.png">

Will try dyeing his moustache tomorrow... :)

**Comment by DragonflyStats** [comment]
I like the Natty Boh Idea - but I don't think we could use it on any
official channels - unless someone has got an contact at the company.

A logo that features an absolute splendid moustache is fair game though

The Channels have been updated

 - www.twitter.com/JuliaConOrg
 - www.facebook/JuliaConOrg

Would it possible to get the nightscape shot of Baltimore superimposed by
JuliaCon details?

Regards
Kevin O'Brien

**Comment by jpfairbanks** [comment]
Baltimore Skyline: 

![image](https://user-images.githubusercontent.com/2753998/50115802-72cbb680-0216-11e9-8ebe-ca1c85b16a4c.png)

**Comment by cormullion** [comment]
Well, I don't want to get sued by a multinational corporation, so I'll take it no further than [this](https://github.com/cormullion/Boh.jl) - but it was interesting!

**Comment by StefanKarpinski** [comment]
What about making the eye green and the mustache "lobes" red and purple?
