### ISSUE TITLE
Scour the old/unused email addresses from the website

### ISSUE THREAD

**Issue by NHDaly** [JuliaCon/www.juliacon.org#158]
From what I can tell, we used to have two other old email addresses, `juliacon@googlegroups.com` and `contact@juliacon.org`, and I think those both bounce. I opened an issue to verify that here:
 https://github.com/JuliaCon/JuliaCon2019/issues/23

Assuming that's right, we should remove references to those from the website!

**Comment by ViralBShah** [comment]
Yes, best to use `juliacon@julialang.org` everywhere.

**Comment by NHDaly** [comment]
Can I retroactively change the links for the old cons, too?

**Comment by aviks** [comment]
yeah, why not.
