### ISSUE TITLE
Broken link on landing page for "financial assistance" 

### ISSUE THREAD

**Issue by DragonflyStats** [JuliaCon/www.juliacon.org#161]
Hi there

Broken link on landing page for "financial assistance" 

it directs to https://juliacon.org/2019/financial-assistance/ - which is a 404

**Comment by xorJane** [comment]
Has this since been resolved? I don't see a 404.

**Comment by DragonflyStats** [comment]
Seemingly yes. it works for me now too

**Comment by Bubblemelon** [comment]
Hi @DragonflyStats, thanks for opening this issue. The link has been fixed on Feb 13th, see [commit](https://github.com/JuliaCon/www.juliacon.org/commit/3cb0f67dc9c325b6e0d0f565d444baa710bc67e8). :smiley:
