### ISSUE TITLE
Fix start date on website; possibly date formatting

### ISSUE THREAD

**Issue by xorJane** [JuliaCon/www.juliacon.org#163]
From Andrew Claster's email about the 2019 website:

> Note: text below says JuliaCon starts Mon July 22 while image shows Sun July 21 
> 
> Also note: date format in text and image are not American standard. Which is fine: Julia and JuliaCon are intl - no reason why they have to follow American standard, and there may be reasons not to (e.g. communicate global reach, diversity). Just mentioning for awareness, in case this decision was inadvertent.

@essenciary I think you created the images on the website. Is that right? If so, could you update to show the conference start date as Monday, July 22?

**Comment by klkeys** [comment]
Which image is this? I just checked https://juliacon.org/2019 and the image
says "Monday 22nd to Friday 26th of July, 2019"

**Comment by xorJane** [comment]
Ohh my bad. It's actually just a screenshot of the website posted on twitter

[https://twitter.com/JuliaConOrg/status/1100467372601819136](https://twitter.com/JuliaConOrg/status/1100467372601819136
)

that's the issue.

**Comment by essenciary** [comment]
Just for the record, on the website, the date is not part of the image. It's HTML text layered on top of the background image. So no image editing is needed to change that heading.

**Comment by xorJane** [comment]
Thanks for clarifying Adrian!
