### ISSUE TITLE
Can we surface the deadlines for CfP and early-bird ticket sales on the front page?

### ISSUE THREAD

**Issue by NHDaly** [JuliaCon/www.juliacon.org#164]
We should have these dates both on the front page of the site, and probably also on the front page of the Pretalx page.

**Comment by xorJane** [comment]
That's a great point! @Bubblemelon and @essenciary, might either of you have time for this?

**Comment by essenciary** [comment]
@NHDaly @xorJane I see that they are on the website (banner at the top of the page).

**Comment by Bubblemelon** [comment]
I believe @essenciary is refering to the top bar that says "Call for proposals and Early Bird Ticket Sales now open!" 

We could put the deadline for CfPs on that bar and as well as the last day for Early Bird Ticket Sales.

As for the [Pretalx page](https://pretalx.com/juliacon2019/), perhaps the person with access the to JuliaCon Pretalx account might be able include the deadline on that page description.

**Comment by xorJane** [comment]
@NHDaly I just merged Cheryl's PR on this. Is it okay to close this issue?

**Comment by xorJane** [comment]
Actually, sorry, since it doesn't address the Pretalx page, perhaps we should leave it open. @ChrisRackauckas can you edit the pretalx page to make the CfP deadline more visible?

**Comment by ChrisRackauckas** [comment]
Added. Does anyone have a png logo to put on the page as well? Pretalx software update doesn't allow svgs anymore.

**Comment by xorJane** [comment]
Thanks!

**Comment by essenciary** [comment]
@ChrisRackauckas I exported one from the SVG but it has a 
white background. If you need it transparent, let me know, I'll try to make one. 
![logo](https://user-images.githubusercontent.com/11292378/53984646-04faa100-411a-11e9-8933-16064af80068.png)

**Comment by NHDaly** [comment]
Thanks all for taking care of this so quickly!! :)

😁
