### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by Bubblemelon** [JuliaCon/www.juliacon.org#166]
Hi @essenciary :smiley: 

Do we have a favicon made for the website? It seems to me, that there isn't one in the repository. Was there one for previous years?

**Comment by essenciary** [comment]
@BubblemelonI don't think we ever had one. Also, it's tricky as the logo is very wide, while for favicon we need a square. Any ideas?

**Comment by Bubblemelon** [comment]
This is what I've experimented with so far:

![image](https://user-images.githubusercontent.com/12985181/54150401-9f4a3580-43f5-11e9-8b57-93208d4b8de2.png)

For the middle tab, I've simply used the `julia-logo-dots.png` in the `assets` directory for `2019`. I compared it to the JuliaLang website, and it was slightly larger.

I could also use the favicon from julialang.org instead for consistency.

![julialang favicon](https://julialang.org/favicon.ico)

As for the third tab above, I've tried doing this to the logo:

![image](https://user-images.githubusercontent.com/12985181/54151079-38c61700-43f7-11e9-9fd6-751502e24224.png)

![image](https://user-images.githubusercontent.com/12985181/54151521-3b753c00-43f8-11e9-91d6-529173f8ab92.png)

I think making the word "con" smaller would be more visually better:
![image](https://user-images.githubusercontent.com/12985181/54151723-b50d2a00-43f8-11e9-8ea7-80c0138eba5e.png)

**Comment by Bubblemelon** [comment]
Let me know what you think. :smiley: I suppose on the safe side, we could use `julia-logo-dots.png`

**Comment by ViralBShah** [comment]
The juliacon favicon looks good to me.

**Comment by xorJane** [comment]
I like the juliacon favicon where con is a bit smaller :) Thanks @Bubblemelon !
