### ISSUE TITLE
changes to language regarding venue

### ISSUE THREAD

**Issue by vjd** [JuliaCon/www.juliacon.org#175]
The Umaryland marketing team suggested a few wording changes to the text describing the venue. 
1. Change the third line of the main header and add MD to the last line as below
![image](https://user-images.githubusercontent.com/1425562/56005816-56112e00-5ca0-11e9-8873-c46009cfa22d.png)

2. Suggestion to change the top text of the venue box and to spell out the name of the School at the bottom of the map as below
![image](https://user-images.githubusercontent.com/1425562/56005960-04b56e80-5ca1-11e9-87ab-2a8787ee3d6c.png)

**Comment by Bubblemelon** [comment]
From your screenshot above, it looks like the change required for the top text is the addition of the word _Baltimore_ next to SMC Campus Center.

![image](https://user-images.githubusercontent.com/12985181/56083473-56154900-5dda-11e9-83de-a822cc648449.png)

Changes to the header:
![image](https://user-images.githubusercontent.com/12985181/56083541-2dda1a00-5ddb-11e9-8805-e2d68c755fec.png)

**Comment by vjd** [comment]
In the top text, the only change is the addition of Baltimore, that is correct

With regards to the header -

To better explain.. the event is being held at 

University of Maryland Baltimore (UMB)
Baltimore, MD

There is confusion when we just say the **University of Maryland** as most people associate it with the University of Maryland at **College Park** which is a totally different campus. 

So, In the header, please add **_Baltimore_**, before MD, USA

**Comment by Bubblemelon** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/12985181/56086085-1ebb9200-5e04-11e9-8b9e-d2a107417127.png)

**Comment by vjd** [comment]
Yes

**Comment by Bubblemelon** [comment]
Here's the update to the venue details box:

![image](https://user-images.githubusercontent.com/12985181/56154043-7543e000-5f6c-11e9-8fd1-de1d44cf17c5.png)

I find that embedding the map on the website is convenient especially when you don't know the area. Saves the trouble of copy/paste or having to type the destination into google.

**Comment by vjd** [comment]
Thanks @Bubblemelon

**Comment by xorJane** [comment]
Yes, thank you @Bubblemelon !!
