### ISSUE TITLE
Enigmatic variations on the Julia logo 

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/www.juliacon.org#185]
I noticed that the "three dots" logo (below right) used here is slightly darker, using three colors, than the older version (left), which used six colors, with lighter shades of each:

<img width="675" alt="Screenshot 2019-05-15 at 08 51 39" src="https://user-images.githubusercontent.com/52289/57758018-aa1f9000-76ee-11e9-8d13-5a09697a1c6c.png">

I like both, and it's not a problem - but I'm interested to know if it's official/unofficial/accidental ...? 

Discourse also uses this three color version in the full text+logo, as does the main julialang.org website since the redesign (apart from the YouTube button), but the documentation and pkg.julialang.org/docs used the older six color version (unless in dark mode). In the source tree on github, there's [the original 6 color](https://github.com/JuliaLang/julia/blob/master/contrib/julia.svg) version. Icons (at least on macOS), and Wikipedia are six color. Julia Computing uses both a four color version and an eight color version of their logo.

It makes sense to simplify, the outer (darker) circle does appear to vary in thickness as you wander round the ecosystem... 

I admit that this is one of the least important issues ever opened, but I'm curious to know the story.

**Comment by StefanKarpinski** [comment]
The logo used on julialang.org changed during the redesign and then I think this also propagated to the juliacon.org website. I think I rather prefer the new, simpler logo, so I would put my support behind making the new logo official.

**Comment by cormullion** [comment]
Should I venture a PR on the main github site? It will be more helpful than drawing cats, at least. 😸

**Comment by StefanKarpinski** [comment]
Yes, that would be great. Thank you, @cormullion. Also, I love your cat drawings too ❤️

**Comment by vchuravy** [comment]
I should add that I did this redesign for JuliaCon (we used the full colours because it was easier for the t-shirts) and I suspect it propagated  to discourse since it was the files I had on my harddisk.

**Comment by cormullion** [comment]
@vchuravy You chose wisely. 😀
