### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/www.juliacon.org#186]
I spent some time this weekend assembling some graphics. Perhaps there are some ideas here which you can use; if not, no problem, it was fun anyway!

### Square graphic

I like the current JuliaCon banner. However, it does have a high 3:1 aspect ratio, and occasionally you want something which makes better use of a square area, like badges or stickers. Here are a few ideas for more squarish graphics.

![assembly-of-square-designs](https://user-images.githubusercontent.com/52289/57979262-31cd0d80-7a13-11e9-8b9c-512400e2cf4c.png)

Of course, if you want to put a graphic on a pen, say, these wouldn't be very suitable!

### More ideas

For designs that look good on t-shirts, it depends on whether you're printing in one color or many, and whether on dark or light colors. 

A simple one-color idea like this:

![hipster copy 2](https://user-images.githubusercontent.com/52289/57979317-157da080-7a14-11e9-94b1-ded0a51f2a1b.png)

looks like this when mocked up:

 ![hipster](https://user-images.githubusercontent.com/52289/57979277-68a32380-7a13-11e9-90a9-0ec952c9ab7d.png)

(Sorry about the slogan, I couldn't think of anything wittier...;) )

Simpler would be:

![hipster copy](https://user-images.githubusercontent.com/52289/57979356-802edc00-7a14-11e9-8d9c-c388e6de38d9.png)

## Edit

To avoid confusing Julia with Rust, here's a less wheel-like version.

![penrose-hipster](https://user-images.githubusercontent.com/52289/58003333-740c5280-7ad8-11e9-9e70-36013602e776.png)

Vcat the pirate cat is another single-color idea:

![pirate](https://user-images.githubusercontent.com/52289/57979336-52e22e00-7a14-11e9-8004-dd5b2d50f4b1.png)

If you have text, it's nice to have one or more colors. For some text-based ideas, you could go with stuff like this:

![textbased](https://user-images.githubusercontent.com/52289/57979377-b2d8d480-7a14-11e9-8341-ac41c16f0f91.png)

or a little more stylishly:

![multipledispatch](https://user-images.githubusercontent.com/52289/57979380-bbc9a600-7a14-11e9-987b-9d1df87d8b02.png)

Or even use this classic text from way back:

![greedytext](https://user-images.githubusercontent.com/52289/57979382-c421e100-7a14-11e9-8c1d-6a9e827f2681.png)

which could be converted to 1 or 2 colors on a dark background. You'd have people stopping you in the street asking to read your t shirt, though... 

### Even more

Moving slowly and inexorably into left field, we'd have things like this:

![planetjulia-1-π60](https://user-images.githubusercontent.com/52289/57979430-7063c780-7a15-11e9-81e5-b67d388610e9.png)

One for the physicists, I suppose:

![cow](https://user-images.githubusercontent.com/52289/57979428-6fcb3100-7a15-11e9-8228-e617005b42e3.png)

I don't know what to make of this one:

![illuminati](https://user-images.githubusercontent.com/52289/57979429-6fcb3100-7a15-11e9-93a3-16cb86594057.png)

but at least it works well on a t shirt; I've put an earlier version of this design on a shirt before, and it looks good on black or red. Being barely legible is half the point. 😂

Does this need color?  It almost works in grey.

<img width="747" alt="Screenshot 2019-05-19 at 11 04 28" src="https://user-images.githubusercontent.com/52289/57980655-f25bec80-7a25-11e9-814b-6b7911d45f70.png">

One minority that's not catered for often enough in the tech world is the Over-40s, so here's some ideas to provoke some nostalgic feelings. Fortunately, ideas are not subject to copyright...

This definitely needs color:

![darkside](https://user-images.githubusercontent.com/52289/57979467-e2d4a780-7a15-11e9-801f-31cdf374f5d0.png)

But this one definitely doesn't:

![pixels](https://user-images.githubusercontent.com/52289/57979474-f3851d80-7a15-11e9-97bf-99c845a3e7a8.png)

(the original used radio wave data from pulsar CP 1919, but this version just scans a rather noisy PNG version of the Julia logo.)

This one would definitely need color:

![julia-jurassic](https://user-images.githubusercontent.com/52289/57979497-5080d380-7a16-11e9-943f-9ddf71a83a02.png)

Yes, it's a bit of a stretch, I know. But the colors are nice.

So if there's anything here you can use, I can probably dig out an SVG or PNG or whatever.

**Comment by ViralBShah** [comment]
I love them all. Get me one of each please!

**Comment by ViralBShah** [comment]
I like the vcat type pirate the best, followed by the dinosaur. 

Needs some mention of Julia or juliacon on the shirt.

**Comment by matbesancon** [comment]
The manifesto one is really cool, I don't know what would be the best format. It feels like a great poster to hang in a lab / office.

But the splat named tuples is terrific! Especially the red-ish version. It would be awesome as a sticker or TShirt. The only drawback is that it looks somehow similar to the Rust logo

**Comment by xorJane** [comment]
These are so great! I especially love the splatting of Named Tuples t-shirt! Also all the sticker ideas.

**Comment by ararslan** [comment]
These are wonderful. Great work as always, @cormullion. I agree with Mathieu that the splatting named tuples design looking a bit too reminiscent of the [Rust logo](https://www.rust-lang.org/logos/rust-logo-512x512.png) though.

For the JuliaCon 2019 images, my favorite is the very top left, `X[1,1]`, followed by `X[4,3]` and `X[3,3]`. For the "even more" images, I love the radio waves and colored BikeShed.jl.

**Comment by cormullion** [comment]
Thanks! 

I added another take on the hipster badge, to avoid re-inventing the Rust logo's wheel.

I was also trying to think of a "one-indexing" slogan, but couldn't.

**Comment by ararslan** [comment]
I really like that new one. The best one-indexing slogan I can think of is "My indices start from one," which kinda sucks. :grimacing:

**Comment by ararslan** [comment]
The one issue I have with these is with the Jurassic Park parody: 1. are there copyright concerns with the design? and 2. people don't really call Julia "JuliaLang," and hopefully they don't start doing so...

**Comment by cormullion** [comment]
1 - Probably not, it's most likely covered under fair use/transformative/parody, and you can't copyright ideas (it's just using colors and shapes that remind you of the original anyway). 2 - Fair point; it probably wouldn't work without it though... 

(I'm not attached to it - it was a stretch, so the concept probably doesn't have legs ... 🦖🦕🦖🦕 )

**Comment by StefanKarpinski** [comment]
So I quite like the prism, the Illuminati and the one based on the [Joy Division pulsar cover art](https://blogs.scientificamerican.com/sa-visual/pop-culture-pulsar-origin-story-of-joy-division-s-unknown-pleasures-album-cover-video/). I also like the less Rust-like [tessellation](https://user-images.githubusercontent.com/52289/58003333-740c5280-7ad8-11e9-9e70-36013602e776.png) image, although I don't really care that much for the "I splat named tuples for breakfast"—I don't really get it, is that a thing that people do in Julia programming that much? Some thoughts:
* For the prism, having the Julia logo in the bottom of the prism might look better.
* For the Illuminati, I think we would want to figure out some really good text—that kind of design really invites a deep read of the small text; maybe we could crowd source some clever text?
* The type pirate cat is cute but I think it's a bit too close to GitHub's Octocat.
* If we could figure out a way to make a Julian version of the original Joy Division/pulsar image, that might be even cooler—that image is public domain, so there's no copyright issue.

**Comment by cormullion** [comment]
> I don't really get it

:) It's just a placeholder, a temporary Lorem Ipsum, but I thought it was quite funny, for some reason. Rejected alternatives included "One language to rule them all", "Just My Type (system)", "Make Arrays Great Again", "Snakes. Why does it always have to be snakes?", "Linter is coming", "Resolving Ousterhout’s Dichotomy since 2012", etc. so you see why I opted for that one.

**Comment by StefanKarpinski** [comment]
> It's just a placeholder, a temporary Lorem Ipsum, but I thought it was quite funny, for some reason.

Ah ok. Yes, it is amusing :)

**Comment by matbesancon** [comment]
+1 for the tessellation one

**Comment by StefanKarpinski** [comment]
Slogan brainstorming...
* "Solving the Two Language Problem since 2012"
* "Dispatching on All Your Arguments"

**Comment by ararslan** [comment]
"All your arguments are belong to dispatch"

**Comment by matbesancon** [comment]
Dispatch me if you can

**Comment by cormullion** [comment]
Ignoring the slogan for now...

I varied some of the parameters of the tile design, found some interesting design axes:

![assemblyvariations](https://user-images.githubusercontent.com/52289/58372205-2ba6c780-7f12-11e9-8f92-18f981e2042a.png)

**Comment by StefanKarpinski** [comment]
Oh man, I love these! I'm really a sucker for the colorful ones but the black and white ones look good too. These will make same great stickers and/or t-shirts.

**Comment by ararslan** [comment]
I think the light colors on white is my favorite design yet! Excellent work!

**Comment by cormullion** [comment]
Some suggestions from a Slack chat:

>"what would white writing on black in these designs look like if you add color to the dots in the “Julia” at center"

and

>"maybe if the tiles were themselves also coloured with the Julia logo colours?"

![assembly-round2](https://user-images.githubusercontent.com/52289/59253971-3ad28880-8c27-11e9-8fa3-7df75c3e831f.png)

You get very little color for your money with the first suggestion... :)

**Comment by StefanKarpinski** [comment]
If we're springing for color, we may as well use it. So my vote would be for colorful (bottom row) and the first or second column since I think that too fine detail will not print as well as coarser detail. I suspect the second column hits the sweet spot between being printable and having an interesting amount of detail.

**Comment by xorJane** [comment]
Ohhh I love these! I prefer the second and later columns strongly to the
first. I'm not totally sure how much detail is too much for printing.
Perhaps the third column would also be okay if the image were large enough.
:)

**Comment by aviks** [comment]
Would the dinosaur one fall foul of copyright? I'm planning on getting stickers or magnets done for the joy division one. And I believe the kaleidoscope one is going on the T-shirt.

**Comment by aviks** [comment]
I can add the Illuminati one on our Numfocus swag store for people to buy? @cormullion do you have high resolution versions for all of these?

**Comment by ViralBShah** [comment]
Dinosaur one may be best avoided for copyright reasons.

**Comment by cormullion** [comment]
Wow, would be cool to see ideas become solid! Like the decisiveness, Avik. 

(You’re probably wise to avoid dinosaurs. There’s no copyright material there, and you can’t copyright an idea, but when you’re spending someone else’s money it’s best to be cautious. 🤓 Being sued by Universal Studios would be something to tell the grandchildren though. It would look nice printed out and put up on the wall of a Hackathon, though....)

I can put up SVGs, PDFs, or in some cases huge PNGs. Probably via Dropbox tomorrow.
