### ISSUE TITLE
Ticket page incorrectly says early-bird tickets are for sale

### ISSUE THREAD

**Issue by christianpeel** [JuliaCon/www.juliacon.org#187]
The page https://juliacon.org/2019/tickets/ says that early-bird tickets are on sale in the headline below the header, and below in the text where the page says 
> Early bird tickets are currently on sale, and will be available until Friday, the 10th of May 2019. After that date, tickets for JuliaCon 2019 will be priced as follows

**Comment by xorJane** [comment]
I just updated the website. Thanks Chris!
