### ISSUE TITLE
Ticket sale link is broken

### ISSUE THREAD

**Issue by rdeits** [JuliaCon/www.juliacon.org#188]
The "Ticket sale" link in the top banner points to `https://juliacon.org/{{current_folder}}/tickets/,  which doesn't exist. Might be related to #183 (per discussion on Slack).

**Comment by ViralBShah** [comment]
Works fine for me. Try force reload page or incognito mode or something?

**Comment by xorJane** [comment]
Whoops, I fixed it yesterday and forgot to update here. Thanks for pinging about this Robin!
