### ISSUE TITLE
Add sponsor logos to website

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCon/www.juliacon.org#189]
I received an email from one of the sponsors checking on when the sponsor logos might be on the website.

**Comment by xorJane** [comment]
How exactly should we do this? Do we want a dedicated page for logos, or should they go at the bottom of the front page?

Last year we had all logos at the bottom of the front page: https://juliacon.org/2018/

@Bubblemelon would you be willing to do this, if we get you a list of all sponsors?

**Comment by ViralBShah** [comment]
They should go on the bottom of the page like last year, since it is a branding opportunity for sponsors.

**Comment by Bubblemelon** [comment]
Yup, count me in. Will be using logos from [#44](https://github.com/JuliaCon/JuliaCon2019/issues/44), and from https://juliacon.org/2018/ for last year's sponsors sponsoring this year (unless otherwise indicated). :smiley:

**Comment by ViralBShah** [comment]
That sounds great!
