### ISSUE TITLE
Add link for Julia Community prizes

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCon/www.juliacon.org#190]
Can we work this into the banner on top?

https://docs.google.com/forms/d/e/1FAIpQLSch3givCyr8lOmgIzI5NaLC8EWBMj4QC2LQCtINfNO4aajZWw/viewform

**Comment by Bubblemelon** [comment]
Resolved in this commit: https://github.com/JuliaCon/www.juliacon.org/commit/a5e20a1b9aba81d0b9699568543379c48fa9d9c8 by Avik.
