### ISSUE TITLE
Suggested updates to JuliaCon 2020 Webpage - Call for Volunteers

### ISSUE THREAD

**Issue by ahclaster** [JuliaCon/www.juliacon.org#196]
Suggested updates to JuliaCon 2020 Webpage.

Call for Volunteers

a. Add Call for Volunteers to landing page (menu bar and content box)
b. Create / update signup forms from 2019 to 2020 - mentors, proceedings reviewers, financial assistance application reviewers, talk submission reviewers, local/onsite volunteers - and include links to update signup forms on Volunteer page

**Comment by ahclaster** [comment]
Volunteer page should include links to apply to be a mentor, apply to review proposals, apply to review proceedings, apply to review financial aid applications, local/onsite volunteer.

**Comment by aviks** [comment]
some of this was actioned earlier.
