### ISSUE TITLE
Suggested update to JuliaCon 2020 Webpage - Sponsorship

### ISSUE THREAD

**Issue by ahclaster** [JuliaCon/www.juliacon.org#198]
Suggested update to JuliaCon 2020 Webpage - Sponsorship

Sponsorship - add Call for Sponsor content box to landing page with link to sponsorship page

**Comment by aviks** [comment]
This is done

**Comment by aviks** [comment]
For the record, fixed by : https://github.com/JuliaCon/www.juliacon.org/commit/a6ee4d9a43934c546eeaa04e524e8cba410d195d
