### ISSUE TITLE
Suggested update to JuliaCon 2020 Webpage - add banner to landing page with link and deadline for Early Bird tickets

### ISSUE THREAD

**Issue by ahclaster** [JuliaCon/www.juliacon.org#199]
Suggested update to JuliaCon 2020 Webpage

Add banner across the top of landing page with link and deadline to purchase Early Bird tickets

**Comment by aviks** [comment]
I've added a banner. The deadline is a couple of months away, it seems wierd to adverstise the date now. Will add the date nearer the time.
