### ISSUE TITLE
Suggested update to JuliaCon 2020 Web page - ticket purchase

### ISSUE THREAD

**Issue by ahclaster** [JuliaCon/www.juliacon.org#200]
Can the ticket purchase page be made easier to navigate, less confusing? There are a lot of options and discounts: Early Bird pricing, promo code box, student discount and 3 ticket options (talks, workshop, talks + workshop) which together make it difficult to navigate, identify and purchase the proper ticket.

**Comment by logankilpatrick** [comment]
Hey @ahclaster Thanks for the feedback. I agree that it may be confusing when you first look at it. Might it be easier if we made the first choice "Talks + Workshop, Early Bird"? I am not sure how many people actually attend just for the workshops or just for the talks but perhaps they are ordered that way based on their popularity? 

@xorJane any thoughts on this?

**Comment by ViralBShah** [comment]
I don't think there's a whole lot we are going to be able to do differently here.
