### ISSUE TITLE
Some duplicate videos on YouTube playlist

### ISSUE THREAD

**Issue by EricForgy** [JuliaCon/www.juliacon.org#233]
Just FYI, looking at the JuliaCon playlist, it appears there are still a number of duplicate videos.

Here are some that I found on a first pass:

- 45/46: Rocket.jl
- 48/49: DFTK.jl
- 59/60: Tombs
- 140/162: Minsymposium
- 141/159: Beast.jl

There may be others.

cc @logankilpatrick @ViralBShah

**Comment by ViralBShah** [comment]
@aviks

**Comment by logankilpatrick** [comment]
From what I recall, we had multiple conversations to resolve this. Should be good now. Thanks for opening this @EricForgy.

**Comment by logankilpatrick** [comment]
Did just find one other duplicate when I was looking through things.
