### ISSUE TITLE
Get all the group photos into each year's JuliaCon

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCon/www.juliacon.org#235]
We should get these group photos (and other nice photos from each year if there are some) on the relevant parts of the website for each year. 

Also make sure to link the youtube playlist for each year.

**Comment by ViralBShah** [comment]
cc @aviks

**Comment by aviks** [comment]
The 2016 photo is a bit low res, compared to the others. Is there a high res version?

**Comment by ViralBShah** [comment]
I got them all from different sources - so I am not sure if I have a hi-res version. I wonder if @jiahao has a hi-res version for 2016.
