### ISSUE TITLE
Add pay what you can to ticket registration

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCon/www.juliacon.org#264]
Per a thread on slack: 

> I was looking at the Dask approach to their online conference and see they have a "pay-what-you-can pricing model". What's interesting about this is that my employer may be willing to reimburse a "suggested ticket price" in full.
https://summit.dask.org/tickets/

**Comment by logankilpatrick** [comment]
@aviks does eventbrite support this feature?

**Comment by aviks** [comment]
I said on slack: 

> We've considered this in the past, and the advice we've got is that anything optional is difficult to get reimbursed. Most companies and universities have rules saying 'you should pay the minimum amount you can for  stuff', and anything above the mandatory list price falls foul of that. Things like this needs to be accounted as donations, which is a whole different ballgame. 

>This may not be universal, so would be good to get contrary feedback.

**Comment by ViralBShah** [comment]
I think we already have this.
