### ISSUE TITLE
workshop image stretched

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/www.juliacon.org#285]
Thanks for using the image!

But unfortunately it's stretched:

<img width="400" alt="Screenshot 2021-07-19 at 08 47 32" src="https://user-images.githubusercontent.com/52289/126122738-79d5a542-1569-4c35-ae85-89afd645a139.png">

I think (but I'm not sure) that you should use `auto` rather than a specific height. 

```
<img src="/assets/2021/img/poster-workshops.png" alt="Poster for the JuliaCon 2021 workshop schedule" width="100%" height="400">
```

**Comment by logankilpatrick** [comment]
Fixed via 5547750
