### ISSUE TITLE
Missing sponsor in workshop poster

### ISSUE THREAD

**Issue by giordano** [JuliaCon/www.juliacon.org#287]
File [`_assets/2021/img/poster-workshops.png`](https://github.com/JuliaCon/www.juliacon.org/blob/3fc3ca78bf96bab370d16b7548b81732598f099f/_assets/2021/img/poster-workshops.png) is missing DataChef among sponsors.  Also [previews of upcoming workshops](https://www.youtube.com/c/TheJuliaLanguage/videos?view=2&sort=dd&live_view=502&shelf_id=0) on YouTube are missing it.

**Comment by cormullion** [comment]
Have updated thumbnail previews as of 2021-07-21 21:31:57 UTC.

**Comment by cormullion** [comment]
This is another version of the image, with the sponsor added. I'll start up Franklin tomorrow or Friday to add it, but if someone beats me to it, that would be great!

![poster-workshops](https://user-images.githubusercontent.com/52289/126565342-84f3982c-0606-4f37-9b7c-46f505102de8.png)

**Comment by timholy** [comment]
I am always in awe of your visual design. Dang that looks good.

**Comment by cormullion** [comment]
Thanks Tim - one day I'll become a minimalist, but today is not that day... (and I'll write a hyphenation function too)

**Comment by logankilpatrick** [comment]
Fixed via: 1fe9dd7
