### ISSUE TITLE
QXGraphDecompositions.jl Poster

### ISSUE THREAD

**Issue by brenjohn** [JuliaCon/www.juliacon.org#295]
I was due to present a virtual poster with the title "Introducing QXGraphDecompositions" on Friday at 17:25 but I don't see it listed in 2021/posters.md

Is there anything I can do to fix this?

**Comment by logankilpatrick** [comment]
Sorry about this, fixed via https://github.com/JuliaCon/www.juliacon.org/commit/811d8981ed93906d00ca05d577511d2b164925ab
