### ISSUE TITLE
ParameterHandling.jl poster

### ISSUE THREAD

**Issue by willtebbutt** [JuliaCon/www.juliacon.org#296]
I'm not currently able to see the poster for my ParameterHandling.jl submission on [the poster page](https://juliacon.org/2021/posters/), so I'm opening this issue as per the request in an email. This is almost certainly entirely my own fault -- I submitted the short talk as requested, but my mind was stuck in 2019 and I just assumed I'd be able to (virtually) turn up with my poster on the day.

Is it possible to sort this out before the poster session, or have I missed the boat? No problem if it's not possible, I appreciate that everyone must be incredibly busy at the minute!

**Comment by logankilpatrick** [comment]
Please submit the poster recording via the upload link on the website. Send us an email juliacon@julialang.org when it is done and I'll update the website
