### ISSUE TITLE
How to add a link to the keynote speaker section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCon/www.juliacon.org#335]
I tried markdown syntax but it renders as plaintext, any thoughts here @tlienart ?

**Comment by tlienart** [comment]
Hello @logankilpatrick , happy to help but I'm not sure what you're trying to do, could you:

* describe what you want / where you want it
* what you've tried and what didn't work? (maybe point me to a commit on a branch?)

(usually adding a link is just `[name of link](url to link)` but I'm guessing you're trying to do something more sophisticated)

**Comment by logankilpatrick** [comment]
Hey! I tried to do that in in the keynote speaker section but it renders `[name of link](url to link)`. Maybe it has something to do with the special syntax we are using for the keynote speaker section?

**Comment by tlienart** [comment]
that must mean that the place where you tried to add it is an argument for a command or an environment. Try writing explicitly `<a href="def">abc</a>`where you wanted to write `[abc](def)`. (cf slack for conversation)
