### ISSUE TITLE
Social events at JuliaCon 2023

### ISSUE THREAD

**Issue by ranjanan** [JuliaCon/www.juliacon.org#391]
@torkelE some blurb and the signup link.

**Comment by TorkelE** [comment]
This is the form for the RSVP: https://docs.google.com/forms/d/1mF5t04NHpD5VBbwk-trxaDvn9CJSnO3e3nkYkpV8_8g/edit

Depending on where it will be on the website what we write would differ, but something like:
"There will be a variety of social events during JuliaCon 2023. This includes larger events (such as a city tour), and smaller events where we group together people to e.g. go to a restaurant or a bar. To gauge numbers, and to organise groups for the smaller events, please RSVP which events you'd like to attend using the following form: https://docs.google.com/forms/d/1mF5t04NHpD5VBbwk-trxaDvn9CJSnO3e3nkYkpV8_8g/edit"

**Comment by TorkelE** [comment]
Let's not publish the list until end of today, in case there is some additional input.

**Comment by giordano** [comment]
To be clear, are you aware you're posting this on the public repository of the juliacon website?

**Comment by TorkelE** [comment]
Not really (thanks for pointing it out)! Things are ready enough that I don't mind if people who want to sneak around and check it early. It's not public until it is public (even if it is publicly available).

**Comment by ranjanan** [comment]
Thank you for pointing it out @giordano . These were issues to indicate information that is planning to be published on the website.

**Comment by ranjanan** [comment]
@pabloferz can you put information on social events in a new box?

**Comment by ranjanan** [comment]
It's on the website now so I'm closing this
