### ISSUE TITLE
JuliaCon Local Eindhoven: Add JuliaHub Logo as Platinum Sponsor

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#421]
![JuliaHub_Logo](https://github.com/JuliaCon/www.juliacon.org/assets/709029/55fcdc8a-891c-4e92-af74-c6d54d50170c)

**Comment by bvdmitri** [comment]
Will be fixed by #428

**Comment by bvdmitri** [comment]
Fixed by https://github.com/JuliaCon/www.juliacon.org/pull/428
