### ISSUE TITLE
JuilaCon Local Eindhoven 2023: Add JSO as community Sponsor

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#422]
![jso-banner-transparent](https://github.com/JuliaCon/www.juliacon.org/assets/709029/631f44b3-43bf-4e71-a467-6c56eca69405)
![jso-banner](https://github.com/JuliaCon/www.juliacon.org/assets/709029/24bcd006-6b31-4c35-aca7-a3ebb05787c4)

Link to: https://jso.dev/

**Comment by bvdmitri** [comment]
Will be fixed by https://github.com/JuliaCon/www.juliacon.org/pull/428

**Comment by bvdmitri** [comment]
Fixed by #428
