### ISSUE TITLE
JuliaCon Local Eindhoven 2023: Add JuliaLang Eindhoven LinkedIn to the footer or main page of the event.

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#424]
The local Eindhoven team has not setup too many socials, but LinkedIn is working and growing:
https://www.linkedin.com/company/julialang-eindhoven/

Where ever we have discord, volunteers, would be good to also link to LinkedIn.

**Comment by bvdmitri** [comment]
Fixed with #430
