### ISSUE TITLE
JuliaCon Local Eindhoven 2023: package map

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/www.juliacon.org#433]
This is a really cool idea! (Someone must do it for the world... :) 

I think it would read better if you showed the map a bit more clearly.

![eindhoven](https://github.com/JuliaCon/www.juliacon.org/assets/52289/c857c603-2273-464d-8e2c-1e96ee09e097)

**Comment by bvdmitri** [comment]
The event is over
