### ISSUE TITLE
JuliaCon 2024: Can we add photos and after movie from past years?

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#460]

**Comment by bvdmitri** [comment]
Seems like it has been added a while ago 
<img width="582" alt="image" src="https://github.com/JuliaCon/www.juliacon.org/assets/6557701/43bfdfcf-c226-4050-bdac-845a4b3242e6">

**Comment by cityjumper** [comment]
Can we embed the videos so it just appears a bit like PyData does it?Sent from my iPhoneOn 2 May 2024, at 12:53, Bagaev Dmitry ***@***.***> wrote:﻿
Closed #460 as completed.
