### ISSUE TITLE
JuliaCon 2024: Proceedings Tab - do we need it?

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#465]
I believe no one uses the Proceedings... if we don't use it can we remove it?

**Comment by vchuravy** [comment]
There is an active subcommittee for the Julia on proceedings and as far as I am aware it is an ongoing effort for 2024

**Comment by bvdmitri** [comment]
I guess then the answer is yes, we need it. So I close the issue.
