### ISSUE TITLE
JuliaCon 2024: Social Media links

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#467]
We have only Twitter and LinkedIn. 

Can we change the icon of Twitter?
Can we add other relevant social media channels? Slack, Discord, Discourse, Instagram, ....

**Comment by DragonflyStats** [comment]
We have three social media assets that are *specific* to JuliaCon
 - LinkedIn
 - Twitter (now X)
 - (recently added) Bluesky

Constructively we could add Youtube to that list - as most of the content on the Julia channel is from JuliaCons.
I reckon to seperate the others into a different category - as community assets for the Julia language (which is outside of scope for us)

**Comment by pabloferz** [comment]
@cityjumper what do you see for the Twitter icon here?

**Comment by cityjumper** [comment]
@pabloferz now it is right with the X, when I created the issue I saw Twitter logo. I still like @DragonflyStats idea of the Youtube Videos and maybe adding Bluesky
