### ISSUE TITLE
JuliaCon 2024: Venue / Tourist Information

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#471]
Can we add a page that helps people with:

- [x] Accomodation - here are some hotels: Hotel La Riene https://www.booking.com/Share-lgQZ61 , Holiday Inn: 400 EUROS for 3 nights: https://www.booking.com/Share-6JDVqA , The Social Hub 317 EUROS: https://www.booking.com/Share-wU7JztU , WestCord 340 EUR: https://www.booking.com/Share-IBr3Ak8
- [x] Practical information (e.g. https://juliacon.org/local/eindhoven2023/venue/)
- [x] How to get there from Eindhoven Airport, From Amsterdam Airport, Parking, Bikes, renting scooters, bikes
- [x] Here is the main tourist center in Eindhoven: https://www.thisiseindhoven.com/en

**Comment by bvdmitri** [comment]
- [ ] Practical information for individuals for disability on the PSV stadium itself

**Comment by pabloferz** [comment]
Closed by #474
