### ISSUE TITLE
Phrasing on sponsor page

### ISSUE THREAD

**Issue by cormullion** [JuliaCon/www.juliacon.org#488]
> Last year, JuliaCon was held at MIT in Boston, USA. This year, we are thrilled to be returning in-person to Europe.

This reads awkwardly - implying that being back in Europe is better than being in Boston. 

I think the ‘thrill’ was returning to in-person (after the pandemic).

**Comment by cormullion** [comment]
This change has just been reverted?

**Comment by bvdmitri** [comment]
Well, the phrasing has changed since. The thrill now is returning to Europe since 2018. Do you think it still reads awkwardly?

**Comment by cormullion** [comment]
I suppose it still does, to me, but ask an American 😂 

Also you need a ‘s’ after ‘developer’.
