### ISSUE TITLE
JuliaCon: Venue 

### ISSUE THREAD

**Issue by cityjumper** [JuliaCon/www.juliacon.org#518]
Can we add the following hotels for the event.

See attachment. 
[Hotels JuliaCon (2).pdf](https://github.com/JuliaCon/www.juliacon.org/files/14301695/Hotels.JuliaCon.2.pdf)

**Comment by pabloferz** [comment]
The hotels are already in the website. But maybe there are not easily discoverable. I'll fix that instead.

**Comment by pabloferz** [comment]
Oh. I see there are some highlighted new hotels at the end. I'll add those.

**Comment by pabloferz** [comment]
Closed by #519
