### ISSUE TITLE
Jeffrey Sarnoff Sponsorship

### ISSUE THREAD

**Issue by rayegun** [JuliaCon/www.juliacon.org#552]
Hi, please add Jeffrey Sarnoff under a 5k sponsorship. Ideally with this logo:
![JuliaConJs](https://github.com/JuliaCon/www.juliacon.org/assets/9300055/782b5c36-d781-4549-8d84-d64ee51aae4c)

@mkitti we discussed the financials on Slack, and you can message me there for more questions.

**Comment by mkitti** [comment]
OK. Approved. Oh, this is an issue.
