### ISSUE TITLE
Local conferences not findable

### ISSUE THREAD

**Issue by siouxmathware** [JuliaCon/www.juliacon.org#612]
I was looking for some info on last year's local conference in Eindhoven, but could not find any reference to it on the JuliaCon website and had to resort to Google. (This has been likened by someone to having to go on the street and ask where to find rooms in a certain building [citation needed].)

Is there a way to make the local conferences findable within the main JuliaCon site?

**Comment by carstenbauer** [comment]
You have to click on 2023 in the top right corner and then you should see this:
<img width="579" alt="Screenshot 2024-07-12 at 08 25 08" src="https://github.com/user-attachments/assets/24529815-41df-4bf4-a9d4-11b3e89be3b3">

**Comment by KeithWM** [comment]
Thanks for pointing that out. Now I know it's there, it's hard to imagine I could not see it initially, I suppose if I'm the first to complain it's probably fine.

**Comment by siouxmathware** [comment]
Thanks for pointing that out. Now I know it's there, it's hard to imagine I could not see it initially, I suppose if I'm the first to complain it's probably fine.
